# https://parklize.blogspot.com/2022/09/tensorflow-recommenders-5-use-dcn-deep.html 

In [6]:
import pandas as pd
ratings=pd.read_csv('C:/Users/401-14/Desktop/30-200/ratings.csv')

In [7]:
# 현재 user_id 값들을 확인합니다.
print(ratings['user_id'].unique())

# 새로운 user_id 값을 생성하기 위한 사전을 만듭니다.
unique_user_ids = ratings['user_id'].unique()
new_user_ids = {old_id: new_id for new_id, old_id in enumerate(unique_user_ids)}

# ratings DataFrame에서 user_id 값을 바꿉니다.
ratings['user_id'] = ratings['user_id'].map(new_user_ids)

# 변경된 user_id 값을 확인합니다.
print(ratings['user_id'].unique())

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [8]:
import pymysql
import pandas as pd

host = '34.64.95.29'
port = 3306
user = 'root'
password = 'acorn1234'
database = 'music'

connection = pymysql.connect(host=host, port=port, user=user, password=password, database=database)

new_song = pd.read_sql_query('SELECT * FROM new_song', connection)

connection.close()

C:\Users\401-14\AppData\Local\Temp\ipykernel_15272\2806383668.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  new_song = pd.read_sql_query('SELECT * FROM new_song', connection)


In [9]:
new_song.head(3)

key        song_name   artist_name  \
0    0  떠나보낼 준비해 둘걸 그랬어           임한별   
1    1       매일 멀어지는 사이      신용재 (2F)   
2    2              U R  태연 (TAEYEON)   

                                               lyric  \
0  너랑 입으려 고른 옷 오늘 받아봤어<br>오래 걸려서 잊고 있었는데<br>곧 있을 ...   
1  우리의 시간은 여기 멈춰버렸고<br>굳어버린 채로 멍하니 서서<br>또 오늘에서<b...   
2  오랫동안 내 마음엔<br>구름 가득 비가 내려<br>따스한 햇살 비추길<br>간절히...   

                                           lyric_str  sentiment_score age  \
0  너랑 입으려 고른 옷 오늘 받아봤어 오래 걸려서 잊고 있었는데 곧 있을 너의 생일에...             -100  34   
1  우리의 시간은 여기 멈춰버렸고 굳어버린 채로 멍하니 서서 또 오늘에서 매일 멀어져 ...               30  33   
2  오랫동안 내 마음엔 구름 가득 비가 내려 따스한 햇살 비추길 간절히 바랬죠 어깨를 ...               -8  34   

  gender                                                url  
0      0  https://i.scdn.co/image/ab67616d0000b273cc1386...  
1      0  https://i.scdn.co/image/ab67616d0000b27323d7e5...  
2      1  https://i.scdn.co/image/ab67616d0000b273f184df...

In [10]:
ratings

user_id                             song_name  user_rating   timestamp
0            0                       떠나보낼 준비해 둘걸 그랬어          5.0  1648900251
1            0                            매일 멀어지는 사이          5.0  1611715172
2            0                                   U R          5.0  1638478729
3            0             비로소 너에게 도착했다 (Full Bloom)          5.0  1671313948
4            0                                  바라보기          4.0  1637858569
...        ...                                   ...          ...         ...
99983      777                 바람 (WIND) (YOON SOLO)          3.0  1634779895
99984      777                       물어 (Prod. 기리보이)          3.0  1655949929
99985      777  I'll Never Love Again (Film Version)          2.0  1601970976
99986      777               Like It (Feat. 행주, 보이비)          1.0  1593483389
99987      777                                   이별주          3.0  1629843800

[99988 rows x 4 columns]

In [16]:
import pandas as pd

# 'new_sentiment_score' 열을 4개의 범주로 나누기
ratings['sentiment_score'] = pd.qcut(ratings['sentiment_score'], 4, labels=False)

# 결과 확인
ratings

user_id                             song_name  user_rating   timestamp  \
0            0                       떠나보낼 준비해 둘걸 그랬어          5.0  1648900251   
1            0                            매일 멀어지는 사이          5.0  1611715172   
2            0                                   U R          5.0  1638478729   
3            0             비로소 너에게 도착했다 (Full Bloom)          5.0  1671313948   
4            0                                  바라보기          4.0  1637858569   
...        ...                                   ...          ...         ...   
99983      777                 바람 (WIND) (YOON SOLO)          3.0  1634779895   
99984      777                       물어 (Prod. 기리보이)          3.0  1655949929   
99985      777  I'll Never Love Again (Film Version)          2.0  1601970976   
99986      777               Like It (Feat. 행주, 보이비)          1.0  1593483389   
99987      777                                   이별주          3.0  1629843800   

       sentiment_score age gender  
0                    0  34      0  
1                    3  33      0  
2                    3  34      1  
3                    2  34      0  
4                    2  42      0  
...                ...  ..    ...  
99983                3  31      0  
99984                0  30      0  
99985                3  30      0  
99986                0  23      0  
99987                1  30      0  

[99988 rows x 7 columns]

In [17]:
ratings['age']=ratings['age'].astype(int)

# Custom function to map age to age groups
def map_age_to_group(age):
    if age < 20:
        return 0
    elif 20 <= age < 30:
        return 1
    elif 30 <= age < 40:
        return 2
    elif 40 <= age < 50:
        return 3
    else:
        return 4

# Apply the custom function to 'age' column
ratings['age'] = ratings['age'].apply(map_age_to_group)
ratings

user_id                             song_name  user_rating   timestamp  \
0            0                       떠나보낼 준비해 둘걸 그랬어          5.0  1648900251   
1            0                            매일 멀어지는 사이          5.0  1611715172   
2            0                                   U R          5.0  1638478729   
3            0             비로소 너에게 도착했다 (Full Bloom)          5.0  1671313948   
4            0                                  바라보기          4.0  1637858569   
...        ...                                   ...          ...         ...   
99983      777                 바람 (WIND) (YOON SOLO)          3.0  1634779895   
99984      777                       물어 (Prod. 기리보이)          3.0  1655949929   
99985      777  I'll Never Love Again (Film Version)          2.0  1601970976   
99986      777               Like It (Feat. 행주, 보이비)          1.0  1593483389   
99987      777                                   이별주          3.0  1629843800   

       sentiment_score  age gender  
0                    0    2      0  
1                    3    2      0  
2                    3    2      1  
3                    2    2      0  
4                    2    3      0  
...                ...  ...    ...  
99983                3    2      0  
99984                0    2      0  
99985                3    2      0  
99986                0    1      0  
99987                1    2      0  

[99988 rows x 7 columns]

In [18]:
ratings.to_csv('C:/Users/401-14/Desktop/30-200/ratings.csv',index=False)

In [22]:
import pymysql
from sqlalchemy import create_engine

host = '34.64.95.29'
port = 3306
user = 'root'
password = 'acorn1234'
database = 'music'

# MariaDB에 데이터프레임 저장
engine = create_engine(f'mysql+pymysql://{user}:{password}@{host}:{port}/{database}')
s_tot=ratings[['user_id','song_name','user_rating','timestamp','sentiment_score','age','gender']]

s_tot.to_sql(name='ratings', con=engine, if_exists='replace', index=False)

99988

In [1]:
import pymysql
import pandas as pd

host = '34.64.95.29'
port = 3306
user = 'root'
password = 'acorn1234'
database = 'music'

connection = pymysql.connect(host=host, port=port, user=user, password=password, database=database)

ratings = pd.read_sql_query('SELECT * FROM ratings', connection)

connection.close()

C:\Users\401-14\AppData\Local\Temp\ipykernel_23936\324515807.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ratings = pd.read_sql_query('SELECT * FROM ratings', connection)


In [2]:
from typing import Dict, Text # for typing hint

import pprint
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_recommenders as tfrs

print(tf.__version__)
print(tfrs.__version__)

c:\Users\401-14\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


2.13.0
v0.7.3


In [74]:
# new_song['song_name'].nunique()

9238

In [76]:
# ratings['user_id'].nunique()

778

In [3]:
ratings.head(2)

user_id        song_name  user_rating   timestamp  sentiment_score  age  \
0        0  떠나보낼 준비해 둘걸 그랬어          5.0  1648900251                0    2   
1        0       매일 멀어지는 사이          5.0  1611715172                3    2   

   gender  
0       0  
1       0

In [3]:
ratings_dataset = tf.data.Dataset.from_tensor_slices({
    'user_id': ratings['user_id'].values,
    'song_name': ratings['song_name'].values,
    'user_rating': ratings['user_rating'].values,
    'sentiment_score' : ratings['sentiment_score'].values,
    'age' : ratings['age'].values,
    'gender' : ratings['age'].values,
})

new_song_dataset = tf.data.Dataset.from_tensor_slices({
    'song_name': ratings['song_name'].values,  
})

In [5]:
for data in ratings_dataset.take(5):
    print(data)

{'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'song_name': <tf.Tensor: shape=(), dtype=string, numpy=b'\xeb\x96\xa0\xeb\x82\x98\xeb\xb3\xb4\xeb\x82\xbc \xec\xa4\x80\xeb\xb9\x84\xed\x95\xb4 \xeb\x91\x98\xea\xb1\xb8 \xea\xb7\xb8\xeb\x9e\xac\xec\x96\xb4'>, 'user_rating': <tf.Tensor: shape=(), dtype=float64, numpy=5.0>, 'timestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1648900251>, 'sentiment_score': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'age': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'gender': <tf.Tensor: shape=(), dtype=int64, numpy=2>}
{'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'song_name': <tf.Tensor: shape=(), dtype=string, numpy=b'\xeb\xa7\xa4\xec\x9d\xbc \xeb\xa9\x80\xec\x96\xb4\xec\xa7\x80\xeb\x8a\x94 \xec\x82\xac\xec\x9d\xb4'>, 'user_rating': <tf.Tensor: shape=(), dtype=float64, numpy=5.0>, 'timestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1611715172>, 'sentiment_score': <tf.Tensor: shape=(), dtype=int64, numpy=3>, 'age': <tf.Tensor: sha

In [4]:
# timestamps = np.concatenate(list(
#     ratings_dataset.map(lambda x: x['timestamp']).batch(100)))
# max_timestamp = timestamps.max()
# min_timestamp = timestamps.min()

# timestamp_buckets = np.linspace(
#     min_timestamp, max_timestamp, num=1000)

# unique_song_titles
song_titles_list = [x['song_name'] for x in new_song_dataset]
unique_song_titles = np.unique(np.hstack(song_titles_list))

# unique_user_ids
user_ids_list = [x['user_id'] for x in ratings_dataset]
unique_user_ids = np.unique(np.hstack(user_ids_list))

unique_user_ids = [str(uid) for uid in unique_user_ids]
unique_song_titles = [str(title) for title in unique_song_titles]
print(len(unique_song_titles), len(unique_user_ids))

9238 778


In [50]:
# timestamp + 감성점수 + 나이 + 성별
class UserModel(tf.keras.Model):

    def __init__(self, use_timestamps):
        super().__init__()

        self._use_timestamps = use_timestamps

        # User id embedding
        self.user_embedding = tf.keras.Sequential([
            tf.keras.layers.StringLookup(
                vocabulary=unique_user_ids,
                mask_token=None),
            tf.keras.layers.Embedding(len(unique_user_ids) + 1, 32)
        ])


        # Sentiment score embedding
        self.sentiment_score_embedding = tf.keras.Sequential([
            tf.keras.layers.Embedding(6, 16)  
        ])

        # Age embedding
        self.age_embedding = tf.keras.Sequential([
            tf.keras.layers.Embedding(7, 16)  
        ])

        # Gender embedding
        self.gender_embedding = tf.keras.Sequential([
            tf.keras.layers.Embedding(10, 16)  
        ])

    def call(self, inputs):
        if not self._use_timestamps:
            return self.user_embedding(inputs['user_id'])

        return tf.concat([
            self.user_embedding(inputs['user_id']),
            self.sentiment_score_embedding(inputs['sentiment_score']),
            self.age_embedding(inputs['age']),
            self.gender_embedding(inputs['gender']),
        ], axis=1)


In [13]:
class SongModel(tf.keras.Model):

    def __init__(self, use_title_text=True,output_dim=80):
        super().__init__()
        max_tokens=1_000
        self.use_title_text = use_title_text

        self.title_embedding = tf.keras.Sequential([
            tf.keras.layers.StringLookup(
                vocabulary=unique_song_titles, mask_token=None),
            tf.keras.layers.Embedding(len(unique_song_titles)+1, 32)
        ])

        if use_title_text:
            self.title_vectorizer = tf.keras.layers.TextVectorization(
                max_tokens=max_tokens)
            self.title_vectorizer.adapt(new_song_dataset.map(lambda x: x['song_name']))

            self.title_text_embedding = tf.keras.Sequential([
                self.title_vectorizer,
                tf.keras.layers.Embedding(max_tokens, 32, mask_zero=True),
                tf.keras.layers.GlobalAveragePooling1D()
            ])
        
    def call(self, inputs):
        if not self.use_title_text:
            return self.title_embedding(inputs['song_name'])
        
        title_embedding = self.title_embedding(inputs['song_name'])
        title_text_embedding = self.title_text_embedding(inputs['song_name'])
        return tf.concat([title_embedding, title_text_embedding], axis=1)


In [51]:
class MovielensModel(tfrs.models.Model):
    
    def __init__(self, use_timestamps=False, use_title_text=True):
        super().__init__()
        
        self.rating_weight = 0.5
        self.retrieval_weight = 0.5

        # 총 고유 'user_id' 값의 개수를 계산합니다.
        num_unique_users = ratings['user_id'].nunique() + 1
        
        # 사용자 모델의 임베딩 레이어 크기를 num_unique_users로 설정합니다.
        self.user_model = tf.keras.Sequential([
            tf.keras.layers.Embedding(num_unique_users, 32),
            tf.keras.layers.Dense(32, activation="relu"),
        ])
        
        self.song_model = tf.keras.Sequential([
            SongModel(use_title_text),
            tf.keras.layers.Dense(80)
        ])
        self.sentiment_embedding = tf.keras.layers.Embedding(6, 16)
        self.age_embedding = tf.keras.layers.Embedding(7, 16)
        self.gender_embedding = tf.keras.layers.Embedding(10, 16)

        # Ranking model with DCN using keras Functional API
        x0 = tf.keras.Input(shape=(160,))
        x1 = tfrs.layers.dcn.Cross()(x0, x0)
        x2 = tfrs.layers.dcn.Cross()(x0, x1)
        d1 = tf.keras.layers.Dense(256, activation='relu')(x2)
        d2 = tf.keras.layers.Dense(64, activation='relu')(d1)
        output = tf.keras.layers.Dense(1)(d2)
        self.rating_model = tf.keras.Model(inputs=x0, outputs=output)
    
        # Multi-tasks
        self.rating_task: tf.keras.layers.Layer = tfrs.tasks.Ranking(
            loss=tf.keras.losses.MeanSquaredError(),
            metrics=[tf.keras.metrics.RootMeanSquaredError()]
        )
        self.retrieval_task: tf.keras.layers.Layer = tfrs.tasks.Retrieval(
            metrics=tfrs.metrics.FactorizedTopK(
                candidates=new_song_dataset.batch(128).map(self.song_model)
            )
        )
    def call(self, features: Dict[Text, tf.Tensor]) -> tf.Tensor:
        user_embeddings = self.user_model(features['user_id'])
        sentiment_embed = self.sentiment_embedding(features['sentiment_score'])
        age_embed = self.age_embedding(features['age'])
        gender_embed = self.gender_embedding(features['gender'])
        user_embeddings = tf.concat([user_embeddings, sentiment_embed, age_embed, gender_embed], axis=1)
        
        # user_embeddings = self.user_model(features['user_id'])
        song_embeddings = self.song_model({'song_name': features['song_name']})

        return (
            user_embeddings, 
            song_embeddings,
            self.rating_model(tf.concat([user_embeddings, song_embeddings], axis=1))
        )        

    def compute_loss(self, features: Dict[Text, tf.Tensor], training=False) -> tf.Tensor:
        user_embeddings, song_embeddings, rating_predictions = self(features)

        # 'song_embeddings'를 'tfrs.metrics.FactorizedTopK' 메트릭스에 전달
        retrieval_loss = self.retrieval_task(user_embeddings, song_embeddings)
        rating_loss = self.rating_task(
            labels=features['user_rating'],
            predictions=rating_predictions
        )

        return (self.rating_weight * rating_loss + self.retrieval_weight * retrieval_loss)



In [11]:
tf.random.set_seed(7)
shuffled = ratings_dataset.shuffle(9_000, seed=7,
                reshuffle_each_iteration=False)

train = shuffled.take(7_200)
test = shuffled.skip(7_200).take(1_800)

cached_train = train.shuffle(7_200).batch(50).cache()
cached_test = test.batch(10).cache()

In [56]:
model = MovielensModel(use_timestamps=True, use_title_text=True)
model.compile(optimizer=tf.keras.optimizers.Adagrad(0.1))

model.fit(cached_train, epochs=3,steps_per_epoch=10)#steps_per_epoch=5

train_acc = model.evaluate(
    cached_train, return_dict=True)['factorized_top_k/top_100_categorical_accuracy']
test_acc = model.evaluate(
    cached_test, return_dict=True)['factorized_top_k/top_100_categorical_accuracy']

print(f'Top-100 accuracy (train): {train_acc:.2f}')
print(f'Top-100 accuracy (test): {test_acc:.2f}')

Epoch 1/3
10/10 [==============================] - 5s 425ms/step - root_mean_squared_error: 3.8371 - factorized_top_k/top_1_categorical_accuracy: 0.1060 - factorized_top_k/top_5_categorical_accuracy: 0.1060 - factorized_top_k/top_10_categorical_accuracy: 0.1060 - factorized_top_k/top_50_categorical_accuracy: 0.1180 - factorized_top_k/top_100_categorical_accuracy: 0.1260 - loss: 104.8620 - regularization_loss: 0.0000e+00 - total_loss: 104.8620
Epoch 2/3
10/10 [==============================] - 4s 425ms/step - root_mean_squared_error: 0.9533 - factorized_top_k/top_1_categorical_accuracy: 0.0120 - factorized_top_k/top_5_categorical_accuracy: 0.0120 - factorized_top_k/top_10_categorical_accuracy: 0.0120 - factorized_top_k/top_50_categorical_accuracy: 0.0160 - factorized_top_k/top_100_categorical_accuracy: 0.0220 - loss: 98.2201 - regularization_loss: 0.0000e+00 - total_loss: 98.2201
Epoch 3/3
180/180 [==============================] - 73s 408ms/step - root_mean_squared_error: 0.5054 - fact

In [34]:
print(ratings['age'].nunique())
print(ratings['gender'].nunique())
print(ratings['sentiment_score'].nunique())

5
2
4


In [337]:
model.evaluate(cached_test,steps=1, return_dict=True)

1/1 [==============================] - 1s 551ms/step - root_mean_squared_error: 1.4394 - factorized_top_k/top_1_categorical_accuracy: 0.0151 - factorized_top_k/top_5_categorical_accuracy: 0.0242 - factorized_top_k/top_10_categorical_accuracy: 0.0344 - factorized_top_k/top_50_categorical_accuracy: 0.0723 - factorized_top_k/top_100_categorical_accuracy: 0.0942 - loss: 17035.7852 - regularization_loss: 0.0000e+00 - total_loss: 17035.7852


{'root_mean_squared_error': 1.4393696784973145,
 'factorized_top_k/top_1_categorical_accuracy': 0.01513671875,
 'factorized_top_k/top_5_categorical_accuracy': 0.024169921875,
 'factorized_top_k/top_10_categorical_accuracy': 0.034423828125,
 'factorized_top_k/top_50_categorical_accuracy': 0.072265625,
 'factorized_top_k/top_100_categorical_accuracy': 0.09423828125,
 'loss': 17035.78515625,
 'regularization_loss': 0,
 'total_loss': 17035.78515625}

In [68]:
test_ratings = {}
for m in train.take(1000):
    user_id = float('11')  
    _, _, test_ratings[m['song_name'].numpy()] = model(
        {'user_id': np.array([user_id]), 
         'song_name': np.array([m['song_name'].numpy()]),
         'sentiment_score': np.array([3]),
         'age': np.array([1]),
         'gender': np.array([1]),
        }
    )
for m in sorted(test_ratings, key=test_ratings.get, reverse=True):
    if isinstance(m, bytes):
        m_decoded = m.decode('utf-8')
    else:
        m_decoded = m
    print(m_decoded)

돌멩이
별의노래(Feat.유진박)
Rager teenager!
폰서트
그녀의 웃음소리뿐
Obliviate
추격자
웃으며 넘길래
포장마차
한사람
처음처럼
거꾸로 강을 거슬러 오르는 저 힘찬 연어들처럼
Dali, Van, Picasso
있다면
해야 (Sunrise)
언젠가는
동감애
Then
이밤
Experience
이방인
놀이공원
Roller Coaster
Rest
수취인 불명
한숨
Guilty Conscience
추억의 책장을 넘기면
숨바꼭질
2411
소년에게
HandClap
호르몬 전쟁
노래해
떼굴떼굴
그리워하다
괜찮아요
로켓트
물론
상처투성이
Untouchable
죄와벌
아니라고
그날처럼
그리워해요
열애중
다음 생
피카부 (Peek-A-Boo)
리듬 타 (RHYTHM TA)
247
사랑했나봐
음파음파 (Umpah Umpah)
UGLY
환승입니다
노력
지켜줄게
ANL
남과 여 (Feat.김범수)
Boo
SILENCE
은인
상상더하기
Jopping
5 Gawd
살다가
물그림
사랑도... 이별도...
그곳에 서서
FIVE
돌아갈래요
10,000 Hours
상하차
Paris
품
응급실
꿈처럼 내린
청개구리
Moments
별거 아니라고
아라리
좋아해줘
Shadow
다가와서
녹턴 (Nocturn)
사랑..그게 뭔데
섬
앵무새
Memorize
상수역
취했나봐
그림자
사랑니
열정
바람기억
숨이 차
전설
전부 너였다
사진
24/7
끝이 아니기를...
POP/STARS
천사가 되겠어
님아
러시안 룰렛 (Russian Roulette)
1llusion
땡땡땡
Palace
idontwannabeyouanymore
Sequence
울지마
1st
24HRS
MILK
행복하세요
클라이막스
J에게
Amsterdam
21
No.1
미완예찬 (未完禮讚)
어떤가요 그댄
놀이공원 (Amusement Park)
신데렐라 (Cinderella)
러브 쉿!
안녕하세요
거침없이
Honesty
광(狂)
마치 흘러가는 바람처럼
시공간
With*One
그대라서
이바보
bellyache
HERO
1월
FIN

In [69]:
test_ratings

{b'Always Awake (Bonus Track)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.3533773]], dtype=float32)>,
 b'My My': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.3292556]], dtype=float32)>,
 b'\xeb\x8f\x8c\xeb\xa9\xa9\xec\x9d\xb4': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.4981165]], dtype=float32)>,
 b'Love Is Gone (Acoustic)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.385724]], dtype=float32)>,
 b'\xeb\xb3\x84\xec\x9d\x98\xeb\x85\xb8\xeb\x9e\x98(Feat.\xec\x9c\xa0\xec\xa7\x84\xeb\xb0\x95)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.4981165]], dtype=float32)>,
 b'Rager teenager!': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.4981165]], dtype=float32)>,
 b'\xec\x9e\x98\xea\xb0\x80 (Feat. Paloalto)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.439547]], dtype=float32)>,
 b'\xed\x8f\xb0\xec\x84\x9c\xed\x8a\xb8': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.4981165]], dtype=float32)>,
 

In [62]:
test_ratings

{b'Always Awake (Bonus Track)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.400264]], dtype=float32)>,
 b'My My': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.3863225]], dtype=float32)>,
 b'\xeb\x8f\x8c\xeb\xa9\xa9\xec\x9d\xb4': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.5300555]], dtype=float32)>,
 b'Love Is Gone (Acoustic)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.4341884]], dtype=float32)>,
 b'\xeb\xb3\x84\xec\x9d\x98\xeb\x85\xb8\xeb\x9e\x98(Feat.\xec\x9c\xa0\xec\xa7\x84\xeb\xb0\x95)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.5300555]], dtype=float32)>,
 b'Rager teenager!': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.5300555]], dtype=float32)>,
 b'\xec\x9e\x98\xea\xb0\x80 (Feat. Paloalto)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.486857]], dtype=float32)>,
 b'\xed\x8f\xb0\xec\x84\x9c\xed\x8a\xb8': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.5300555]], dtype=float32)>,
 

In [380]:
import pickle
song_name_to_key_dict = new_song.set_index('song_name')['key'].to_dict()

print(song_name_to_key_dict)

with open('C:/Users/401-14/Desktop/30-200/song_name_to_key_dict.pkl', 'wb') as f:
    pickle.dump(song_name_to_key_dict, f)

{'떠나보낼 준비해 둘걸 그랬어': 0, '매일 멀어지는 사이': 1, 'U R': 2, '비로소 너에게 도착했다 (Full Bloom)': 3, '바라보기': 4, '동경': 5, '그대라는 시': 6, '아버지 구두': 7, '신촌에 왔어': 8, "넌 나의 전부 (I can't take my eyes off you)": 9, '고백': 10, '너 없는 시간들': 11, '말해! 뭐해?': 12, '형 (兄)': 13, '니 소식': 14, 'Day By Day': 15, '왼손 (Feat. 신지후 Of 포스트맨)': 16, '거짓말': 17, '사랑 이딴 거': 18, '집 (feat. 이소라)': 19, '몇 년 후에': 20, '이별하러 가는 길': 21, '뚜두뚜두 (DDU-DU DDU-DU)': 22, '사랑했었다 (Still love you)': 23, '날 웃게 하는 건 (강균성 Solo)': 24, '이 별': 25, 'My Way': 26, '눈사람': 27, '그 길에': 28, '또 운다 또': 29, '미행': 30, '함께': 31, "I'll Be Yours": 32, '좋은걸 어떡해': 33, '약속': 34, '너라서 사랑해 (Piano Ver.)': 35, 'Aitai / あいたい (보고싶어)': 36, '한여름날의 꿈 (Duet With 옥주현)': 37, '내사람': 38, 'Tenderness': 39, '사랑하길 정말 잘했어요': 40, '꽃잎': 41, '느림보': 42, '우습지': 43, 'Untouchable': 44, '사랑과 우정 사이': 45, '슬픔활용법': 46, '나만의 슬픔': 47, 'Gonna Make You Free': 48, '바람과 함께 사라지다': 49, '동감애': 50, '사랑한다 말해줘': 51, '바람만바람만': 52, '비익조': 53, '어린 사랑 (Rock Ver.)': 54, '금기': 55, '세글자': 56, '사랑아 잘가': 57, '사랑하기 때문에 (Feat. SG워

In [411]:
test_ratings = {}
for m in train.take(5):
    user_id = float('1')  
    _, _, test_ratings[m['song_name'].numpy()] = model(
        {'user_id': np.array([user_id]), 
         'timestamp': np.array([1690642800]), # 2023년 7월 30일 값 
         'song_name': np.array([m['song_name'].numpy()])
        }
    )

# Create a dictionary to store the m_decoded values and their corresponding keys
m_decoded_to_key = {}

# Iterate through the test_ratings dictionary and get the keys for the m_decoded values
for m in sorted(test_ratings, key=test_ratings.get, reverse=True):
    if isinstance(m, bytes):
        m_decoded = m.decode('utf-8')
    else:
        m_decoded = m
    m_decoded_to_key[m_decoded] = song_name_to_key_dict[m_decoded]

# Print the m_decoded values and their corresponding keys
for m_decoded, key in m_decoded_to_key.items():
    print(f"m_decoded: {m_decoded}, key: {key}")


m_decoded: 식스틴 (Feat. 창모) (Sixteen), key: 5232
m_decoded: 시차 (We Are) (Feat. 로꼬 & GRAY), key: 911
m_decoded: LATATA, key: 4896
m_decoded: 넘버나인 (No.9), key: 222
m_decoded: 잘가요 내사랑, key: 2046


In [410]:
test_ratings = {}
for m in test.take(5):
    user_id = float('1')  
    _, _, test_ratings[m['song_name'].numpy()] = model(
        {'user_id': np.array([user_id]), 
         'timestamp': np.array([1690642800]), # 2023년 7월 30일 값 
         'song_name': np.array([m['song_name'].numpy()])
        }
    )

# Create an empty list to store the keys
keys_list = []

# Iterate through the test_ratings dictionary and get the keys for the m_decoded values
for m in sorted(test_ratings, key=test_ratings.get, reverse=True):
    if isinstance(m, bytes):
        m_decoded = m.decode('utf-8')
    else:
        m_decoded = m
    key = song_name_to_key_dict[m_decoded]
    keys_list.append(key)

# Print the list of keys
print(keys_list[:5])


[1161, 1862, 2268, 2299, 2497]


In [441]:
type(test)

tensorflow.python.data.ops.take_op._TakeDataset

In [443]:
test_ratings

{b'\xec\x8b\x9d\xec\x8a\xa4\xed\x8b\xb4 (Feat. \xec\xb0\xbd\xeb\xaa\xa8) (Sixteen)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.7478229]], dtype=float32)>,
 b'\xec\x8b\x9c\xec\xb0\xa8 (We Are) (Feat. \xeb\xa1\x9c\xea\xbc\xac & GRAY)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.7478229]], dtype=float32)>,
 b'LATATA': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.7478229]], dtype=float32)>,
 b'\xeb\x84\x98\xeb\xb2\x84\xeb\x82\x98\xec\x9d\xb8 (No.9)': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.7478229]], dtype=float32)>,
 b'\xec\x9e\x98\xea\xb0\x80\xec\x9a\x94 \xeb\x82\xb4\xec\x82\xac\xeb\x9e\x91': <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.7478229]], dtype=float32)>}

In [444]:
def recommend2():
    user_id = float('1')
    timestamp = 1690642800
    test_ratings = {}

    for m in test.take(100):
        _, _, test_ratings[m['song_name'].numpy()] = model({
            'user_id': np.array([user_id]),
            'timestamp': np.array([timestamp]),
            'song_name': np.array([m['song_name'].numpy()])
        })

    keys_list = []
    for m in sorted(test_ratings, key=test_ratings.get, reverse=True):
        if isinstance(m, bytes):
            m_decoded = m.decode('utf-8')
        else:
            m_decoded = m
        key = song_name_to_key_dict[m_decoded]
        keys_list.append(key)

    return keys_list[:5]

# Call the recommend2 function and get the top 5 recommended song keys
recommended_song_keys = recommend2()
print(recommended_song_keys)


[1161, 1862, 2268, 2299, 2497]


In [445]:
import pickle

with open('C:/Users/401-14/Desktop/30-200/test_ratings.pkl', 'wb') as f:
    pickle.dump(test_ratings, f)


In [379]:
import pickle

# 모델 생성
model = MovielensModel(use_timestamps=True, use_title_text=True)

# Compile the model (You can use your custom loss and optimizer here)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.1))

# Fit the model to your data
model.fit(cached_train, epochs=3,steps_per_epoch=10)

# 모델 저장 시 사용할 파일 경로
model_file = 'C:/Users/401-14/Desktop/30-200/DCN.pkl'

# 모델을 직렬화하여 파일로 저장
with open(model_file, 'wb') as f:
    pickle.dump(model, f)

# # 모델을 불러오기 위해 저장된 파일을 열어서 모델을 불러옵니다.
# with open(model_file, 'rb') as f:
#     loaded_model = pickle.load(f)


Epoch 1/3
10/10 [==============================] - 3s 105ms/step - root_mean_squared_error: 111.4196 - factorized_top_k/top_1_categorical_accuracy: 0.2320 - factorized_top_k/top_5_categorical_accuracy: 0.2445 - factorized_top_k/top_10_categorical_accuracy: 0.2547 - factorized_top_k/top_50_categorical_accuracy: 0.3187 - factorized_top_k/top_100_categorical_accuracy: 0.3422 - loss: 5957.1826 - regularization_loss: 0.0000e+00 - total_loss: 5957.1826
Epoch 2/3
10/10 [==============================] - 1s 99ms/step - root_mean_squared_error: 6.0540 - factorized_top_k/top_1_categorical_accuracy: 0.3891 - factorized_top_k/top_5_categorical_accuracy: 0.3891 - factorized_top_k/top_10_categorical_accuracy: 0.3898 - factorized_top_k/top_50_categorical_accuracy: 0.3914 - factorized_top_k/top_100_categorical_accuracy: 0.3945 - loss: 365.6021 - regularization_loss: 0.0000e+00 - total_loss: 365.6021
Epoch 3/3
10/10 [==============================] - 1s 100ms/step - root_mean_squared_error: 5.0704 - fa

In [324]:
# 데이터를 로드할 때 배치 사이즈를 128로 설정
cached_train = train.shuffle(100_000).batch(128)

# 모델 생성
model = MovielensModel(use_timestamps=True, use_title_text=True)

# Compile the model (You can use your custom loss and optimizer here)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001))

# Fit the model to your data
model.fit(cached_train, epochs=3)

# 모델 저장 시 사용할 파일 경로
model_file = 'C:/Users/401-14/Desktop/30-200/DCN.pkl'

# 모델을 직렬화하여 파일로 저장
with open(model_file, 'wb') as f:
    pickle.dump(model, f)


Epoch 1/3
625/625 [==============================] - 6s 7ms/step - root_mean_squared_error: nan - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: nan - regularization_loss: 0.0000e+00 - total_loss: nan
Epoch 2/3
625/625 [==============================] - 5s 7ms/step - root_mean_squared_error: nan - factorized_top_k/top_1_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_5_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_10_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_50_categorical_accuracy: 0.0000e+00 - factorized_top_k/top_100_categorical_accuracy: 0.0000e+00 - loss: nan - regularization_loss: 0.0000e+00 - total_loss: nan
Epoch 3/3
625/625 [==============================] - 5s 7ms/step - root_mean_squared_error: 